### ISSUE TITLE
Full working demo with source?

### ISSUE THREAD

**Issue by daveeel** [mcissel/FlowTransition#1]
Hi, I'm switching from ccorcos:transitioner + iron-router, the setup of this transitioner seems quite different. 
Is there a demo for this package with source ?

**Comment by mcissel** [comment]
There's no demo.
If you take everything from the [Getting started section](https://github.com/mcissel/FlowTransition/#getting-started) and make a project, that will demonstrate the functionality.

**Comment by jaredtmartin** [comment]
Actually, no, the code in the Getting started section does not work.
first of all, the routes have syntax errors.
Also, I think in the templates you're supposed to use a section template, not just the section tag.  If you actually create a new project with that code you'll see what I mean.  Right now, even after fixing the syntax errors in the routes, you just get a blank screen.  No errors. :-(

Actually, I really want to use this package it would be a godsend for me, but I'm having issues with templates not getting removed after transitioning away in my project, but since the Getting started section is not accurate, I wonder if I'm just not doing it right in the first place.

**Comment by jaredtmartin** [comment]
Also, the two routes in your example have the same path.

**Comment by mcissel** [comment]
You're, right! The routes needs close parens, and they are the same. I'll post a demo, and look into the template section tag blank screen with no error. Please stand by... Then we can work on the template removal

**Comment by mcissel** [comment]
Demo: http://flowtransition.meteor.com/
Demo code: https://github.com/mcissel/flowtransition-demo

**Comment by mcissel** [comment]
Thank you for pointing out the errors in my readme file. I added working code, and made a project with it. I changed the `<section>` tags to `{> section}` tags, and fixed the syntax errors. I added a couple notes on usage. Only block level elements (and their children) are animated. When I first ran it, I saw blank pages, but unlike you, I DID get an error, stating that FlowRouter wasn't found. So I manually added `meteor add kadira:flow-router`, then it worked as expected, including proper removal of the used templates. I think it's fixed.
