### ISSUE TITLE
Do we still need BlazeLayout.render?

### ISSUE THREAD

**Issue by daveeel** [mcissel/FlowTransition#2]
I follow flow-router to have something like:

```
<template name="layout">
  {{>menu}}
  <div class="views">
    {{> Template.dynamic template=main}}
  </div>
</template>
```

Usually we write:

```
BlazeLayout.render('layout', { main: templateName });
```

How to use FlowTransition.flow with this pattern? Can't find example in the readme.

**Comment by mcissel** [comment]
It's all in the [Getting started section](https://github.com/mcissel/FlowTransition/#getting-started)

FlowTransition doesn't use the 'layout' pattern.

``` html
<head>
  <title>Flow-Transition Demo</title>
</head>

<body>
  {{> section name="head"}}
  {{> section name="body"}}
  {{> section name="foot"}}
</body>
```

You don't have to include all the sections every time. E.g.:

``` javascript
if Meteor.isClient
  FlowRouter.route '/',
    name: 'home'
    action: ()->
      FlowTransition.flow({head: "head1"}, {body: "page1"})

  FlowRouter.route '/page2',
    name: 'page2'
    action: ()->
      FlowTransition.flow({head: "head2"}, {body: "page2"}, {foot: "foot1"})
```

So, instead of different layouts, you can just have more sections, and only use them when you want to.  E.g. if you want to have 2 body sections on some pages, use bodyLeftSidebar & bodyMainContent sections, and don't use the single body section.
